import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { RenderProps } from "@src/media/remotion/props";
import { madeControls, mediaUrl, restyle } from "@/lib/site/restyle";
import { SHOWCASES } from "@/lib/site/showcases";

/*
 * The showcase videos that are in the repository (made by `npm run make:showcase` from real runs): each must be
 * something the player can play as it is, and its receipt must add up. Nothing here is generated by the test.
 */
const root = join(__dirname, "../public/showcase");
const slugs = existsSync(root) ? readdirSync(root).filter((name) => !name.startsWith("_") && statSync(join(root, name)).isDirectory()) : [];
/** A published path as a file on disk, by the same rule the page fetches it with. */
const onDisk = (slug: string, shared: string[], path: string) => join(root, "..", mediaUrl(slug, shared, path));

/** Every string in the props that names a file: the values the player will ask for. */
function publishedPaths(props: RenderProps): string[] {
  return [
    ...props.scenes.map((s) => s.src),
    props.captions.style.font.file,
    props.audio.narration,
    ...(props.audio.bgm ? [props.audio.bgm.src] : []),
    ...props.audio.sfx.map((c) => c.src),
    ...(props.brand ? [props.brand.logo] : []),
  ];
}

describe("the showcase videos", () => {
  it("are there, and are the ones the page lists, each under its own name", () => {
    expect(slugs.length).toBeGreaterThanOrEqual(2);
    expect(SHOWCASES.map((s) => s.slug).sort()).toEqual([...slugs].sort());
    // the page's list is written by hand: a video's receipt or script under another video's name would be a lie
    for (const s of SHOWCASES) {
      const file = (name: string) => JSON.parse(readFileSync(join(root, s.slug, name), "utf8")) as unknown;
      expect(s.props, `${s.slug} props`).toEqual(file("props.json"));
      expect(s.looks, `${s.slug} looks`).toEqual(file("looks.json"));
      expect(s.receipt, `${s.slug} receipt`).toEqual(file("receipt.json"));
      expect(s.making, `${s.slug} making`).toEqual(file("making.json"));
    }
  });

  it("publish nothing of the machine or the accounts that made them", () => {
    for (const slug of slugs) {
      for (const name of ["props.json", "looks.json", "receipt.json", "making.json"]) {
        const text = readFileSync(join(root, slug, name), "utf8");
        expect(text, `${slug}/${name}`).not.toMatch(/\/Users\/|\/home\/|\/private\/|runpod:|"runId"|sk_(test|live)_|whsec_/);
      }
    }
  });

  it.each(SHOWCASES.map((s) => [s.slug, s] as const))("%s can be given every look the page offers: each is the player's, and its files are there", (slug, showcase) => {
    const { looks, props } = showcase;
    // as made is what the page starts with
    expect(restyle(props, looks, madeControls(looks))).toEqual(props);
    const made = madeControls(looks);
    for (const captions of Object.keys(looks.captions) as Array<keyof typeof looks.captions>) {
      for (const cuts of Object.keys(looks.cuts) as Array<keyof typeof looks.cuts>) {
        for (const brand of looks.brand ? [true, false] : [false]) {
          const shown = RenderProps.parse(restyle(props, looks, { ...made, captions, cuts, brand, sfx: true, hook: looks.hook !== null }));
          for (const path of publishedPaths(shown)) expect(existsSync(onDisk(slug, looks.shared, path)), `${slug}: ${path} (${captions}, ${cuts})`).toBe(true);
        }
      }
    }
  });

  it.each(slugs)("%s can be played as it is: its props are the player's, and every file they name is there and small", (slug) => {
    const dir = join(root, slug);
    const props = RenderProps.parse(JSON.parse(readFileSync(join(dir, "props.json"), "utf8")));
    const { shared } = JSON.parse(readFileSync(join(dir, "looks.json"), "utf8")) as { shared: string[] };
    for (const path of publishedPaths(props)) {
      expect(existsSync(onDisk(slug, shared, path)), `${slug}/${path}`).toBe(true);
      // nothing a phone on a slow line should have to wait for
      expect(statSync(onDisk(slug, shared, path)).size, `${slug}/${path}`).toBeLessThan(1_500_000);
    }
    expect(existsSync(join(dir, "poster.jpg"))).toBe(true);
    const total = readdirSync(dir, { recursive: true }).map((f) => join(dir, String(f))).filter((f) => statSync(f).isFile()).reduce((sum, f) => sum + statSync(f).size, 0);
    expect(total).toBeLessThan(4_000_000);
  });

  it.each(slugs)("%s has a receipt that adds up and says what made it", (slug) => {
    const receipt = JSON.parse(readFileSync(join(root, slug, "receipt.json"), "utf8")) as { lines: Array<{ label: string; usd: number }>; totalUsd: number; engines: Record<string, string>; seconds: number; scenes: number; topic: string };
    expect(receipt.lines.length).toBeGreaterThan(0);
    expect(Math.round(receipt.lines.reduce((sum, l) => sum + l.usd, 0) * 10_000)).toBe(Math.round(receipt.totalUsd * 10_000));
    expect(receipt.totalUsd).toBeGreaterThan(0);
    for (const part of ["script", "voice", "pictures", "clips"]) expect(receipt.engines[part], part).toMatch(/\S/);
    // where its pictures were made: what the calculator groups the videos by
    expect(["own", "hosted"]).toContain((receipt as { madeOn?: string }).madeOn);
    expect(receipt.seconds).toBeGreaterThan(5);
    expect(receipt.topic).toMatch(/\S/);
  });
});
