import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { RenderProps } from "@src/media/remotion/props";

/*
 * The showcase videos that are in the repository (made by `npm run make:showcase` from real runs): each must be
 * something the player can play as it is, and its receipt must add up. Nothing here is generated by the test.
 */
const root = join(__dirname, "../public/showcase");
const slugs = existsSync(root) ? readdirSync(root).filter((name) => statSync(join(root, name)).isDirectory()) : [];

/** Every string in the props that names a file: the values the player will ask for. */
function publishedPaths(props: RenderProps): string[] {
  return [
    ...props.scenes.map((s) => s.src),
    props.captions.style.font.file,
    props.audio.narration,
    ...(props.audio.bgm ? [props.audio.bgm.src] : []),
    ...props.audio.sfx.map((c) => c.src),
    ...(props.brand ? [props.brand.logo] : []),
  ];
}

describe("the showcase videos", () => {
  it("are there", () => {
    expect(slugs.length).toBeGreaterThanOrEqual(2);
  });

  it.each(slugs)("%s can be played as it is: its props are the player's, and every file they name is there and small", (slug) => {
    const dir = join(root, slug);
    const props = RenderProps.parse(JSON.parse(readFileSync(join(dir, "props.json"), "utf8")));
    for (const path of publishedPaths(props)) {
      expect(existsSync(join(dir, path)), `${slug}/${path}`).toBe(true);
      // nothing a phone on a slow line should have to wait for
      expect(statSync(join(dir, path)).size, `${slug}/${path}`).toBeLessThan(1_500_000);
    }
    expect(existsSync(join(dir, "poster.jpg"))).toBe(true);
    const total = readdirSync(dir, { recursive: true }).map((f) => join(dir, String(f))).filter((f) => statSync(f).isFile()).reduce((sum, f) => sum + statSync(f).size, 0);
    expect(total).toBeLessThan(4_000_000);
  });

  it.each(slugs)("%s has a receipt that adds up and says what made it", (slug) => {
    const receipt = JSON.parse(readFileSync(join(root, slug, "receipt.json"), "utf8")) as { lines: Array<{ label: string; usd: number }>; totalUsd: number; engines: Record<string, string>; seconds: number; scenes: number; topic: string };
    expect(receipt.lines.length).toBeGreaterThan(0);
    expect(Math.round(receipt.lines.reduce((sum, l) => sum + l.usd, 0) * 10_000)).toBe(Math.round(receipt.totalUsd * 10_000));
    expect(receipt.totalUsd).toBeGreaterThan(0);
    for (const part of ["script", "voice", "pictures", "clips"]) expect(receipt.engines[part], part).toMatch(/\S/);
    expect(receipt.seconds).toBeGreaterThan(5);
    expect(receipt.topic).toMatch(/\S/);
  });
});
